### ISSUE TITLE
Meeting 03

### ISSUE THREAD

**Issue by lraynak** [pascalandy/meeting#1]
Agenda for meeting March 1, 2016

https://github.com/pascalandy/meeting/tree/4e9481d2ce4c54ffec67dce4410debf3b1881df3

**Comment by pascalandy** [comment]
**Gary Vaynerchuk**

Marketing and the state of the Internet 
https://www.youtube.com/playlist?list=PLfA33-E9P7FC0AoARnMLvgFgESJe4_Ngs

**Comment by pascalandy** [comment]
Content & Copywriting
http://www.27thlettermedia.com/services.html

**Comment by pascalandy** [comment]
1. From Karla Ramos, thanks for sharing: https://www.tonyrobbins.com/priming-exercise/
2. From Nitzan Gazit, I found this about “Emotional Flood Exercise” on this group Émoticône smile https://www.youtube.com/watch?v=smhzRqHkpZs

**Comment by pascalandy** [comment]
@Luz, let me know about the person you wanted to present me.

> The co-founder challenge

**Comment by pascalandy** [comment]
Here is the video tutorial "How to use Github" 
https://www.youtube.com/watch?v=CkodUCWT7Ro&feature=youtu.be
