### ISSUE TITLE
Jill's 2 Week 2 Item Challenge!

### ISSUE THREAD

**Issue by JillMurwin** [pascalandy/meeting#11]
1. I will create and post at least one YouTube video. 
2.  I will create a lead magnet (aka freebie/giveaway) and link it to the list builder on my website.

No matter what I will complete this task because it would be phenomenally painful to give $500 to:  https://secure.donaldjtrump.com/donate/

**Comment by pascalandy** [comment]
by when? 

![mind-viral-x5ZcHg9BWHkfC](https://media1.giphy.com/media/x5ZcHg9BWHkfC/giphy.gif)

**Comment by JillMurwin** [comment]
:D...By the next meeting on May 10th...:)
