### ISSUE TITLE
Session 09 (2016-05-24)

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#21]
Hey guys,

1) I can't be there tonight. I welcome my aunt at my place and it's the first time we will spend time only the two of us. For everything she did for me, I really can't skip this moment with her. 

2) I'm not sure who will host the meeting tonight, as our main page is not updated. 

See ya in 2 weeks :)
Pascal

**Comment by pascalandy** [comment]
Well ... finally my hunt cancelled me LOL. So I'll be there :)

**Comment by Denisside** [comment]
Greattttttt! Talk to you tonight! :-)

Cheers,

Denis

2016-05-24 15:00 GMT-04:00 Pascal Andy notifications@github.com:

**Comment by pascalandy** [comment]
Here is the TED
http://www.ted.com/talks/david_logan_on_tribal_leadership

**Comment by pascalandy** [comment]
@gonzalezfluz just t make sure you saw the link above :)
