### ISSUE TITLE
Need your feedback: FirePress - the Why

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#23]
Hey guys!
I'm looking for the native english speakers feedback @gonzalezfluz @JillMurwin 

[Here](https://github.com/pascalandy/meeting/blob/master/Pascal%20%E2%80%94%20The%20Why.md) you can hear me saying it :)

[Here](https://github.com/pascalandy/meeting/blob/master/Pascal%20%E2%80%94%20The%20Why.md)  it is my copy titled **Why FirePress**. There are two things to evaluate:

1) The overall feel.
2) The english mistakes I could have made.

Hope this will resonate with you :)

Cheers!
Pascal

**Comment by JillMurwin** [comment]
Hello Pascal

Jumping on a flight to Paris. Will look at this when settled.  I’ll miss the June meetings (middle of the night in France) but will return to the USA July 5th.  

Sending love and hugs….and success energy!

Jill
Chasing ATLAS, LLC
chasingatlas.com
+1 435 225 2563

**Comment by pascalandy** [comment]
Great! Have a nice stay in Paris.

Cheers!
Pascal

On June 5, 2016 at 12:55:56 AM, JillMurwin (notifications@github.com) wrote:

Hello Pascal

Jumping on a flight to Paris. Will look at this when settled. I’ll miss the June meetings (middle of the night in France) but will return to the USA July 5th.

Sending love and hugs….and success energy!

Jill
Chasing ATLAS, LLC
chasingatlas.com
+1 435 225 2563

**Comment by Denisside** [comment]
Hello Pascal! This is great! I love it! I love the tone, the momentum, the impact, the silences, the quality, the music! All is great! I dont see or hear any mistakes! For sure the experts in english will confirm, but for me all is perfect! I am impress and I am as well interested in finding more about your services! Thanks again for asking our inputs and I will talk with you soon. Congratulations again for this greta work!!!! Impressive !!!! Denis

**Comment by gonzalezfluz** [comment]
Hi Pascal, this was awesome! There are some tiny grammatical mistakes here
and there, but I don't think it's an issue. I'm happy to look over the
transcript, but I actually think they add a bit of personality (and
French-speaking background) and don't take away from what you are
presenting. Great job!!

On Tue, Jun 21, 2016 at 3:24 PM, Denis Côté notifications@github.com
wrote:

> Hello Pascal! This is great! I love it! I love the tone, the momentum, the
> impact, the silences, the quality, the music! All is great! I dont see or
> hear any mistakes! For sure the experts in english will confirm, but for me
> all is perfect! I am impress and I am as well interested in finding more
> about your services! Thanks again for asking our inputs and I will talk
> with you soon. Congratulations again for this greta work!!!! Impressive
> !!!! Denis
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/pascalandy/meeting/issues/23#issuecomment-227590627,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANGrP0M3ZoLhBdv6ccp-r5Mtbfrb8JGrks5qOGSEgaJpZM4IuP_F
> .

## 

_Luz C. Gonzalez_
Head of Partnerships
SchoolMint

www.luzcgonzalez.com http://luzcgonzalez.com
https://www.facebook.com/LuzCGonzalezFernandez/
https://www.linkedin.com/in/luz-c-gonzalez-fernandez-00198056
https://www.youtube.com/channel/UCM71Bn_3Ybqfe3Az6qxskvg
https://twitter.com/GonzalezfLuz?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

**Comment by pascalandy** [comment]
@JillMurwin I'll do the video soon, so you don't have to review this anymore :)
