### ISSUE TITLE
Session #11 (June 7th 2016)

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#24]
Hey guys! 
Who is hosting the mastermind tonight? Is it you @juancamou ?

Cheers!

**Comment by gonzalezfluz** [comment]
Hey all, I think it was me but I will need to miss today to ensure that I
vote today! I will have just enough time for this. So sorry about that all!

On Tue, Jun 7, 2016 at 6:24 AM, Pascal Andy notifications@github.com
wrote:

> Hey guys!
> Who is hosting the mastermind tonight? Is it you @juancamou
> https://github.com/juancamou ?
> 
> Cheers!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/pascalandy/meeting/issues/24, or mute the thread
> https://github.com/notifications/unsubscribe/ANGrP3cEwj_paFulukldcEvajyG8Lw3oks5qJXEOgaJpZM4Iv6rS
> .

## 

_Luz C. Gonzalez_
Head of Partnerships
SchoolMint

www.luzcgonzalez.com http://luzcgonzalez.com
https://www.facebook.com/LuzCGonzalezFernandez/
https://www.linkedin.com/in/luz-c-gonzalez-fernandez-00198056
https://www.youtube.com/channel/UCM71Bn_3Ybqfe3Az6qxskvg
https://twitter.com/GonzalezfLuz?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

**Comment by juancamou** [comment]
Hello all,

I will miss today's session, unfortunately my Mother lose her fight against cancer and passed away.
She was a gladiator that fought this fight for 12 years.

What have I learned since last session?
A reminder that life is not forever, today we are here but we don't know about tomorrow and we need to live everyday with passion, love and caring for those who depend on us.

I learned that my mother was loved by way more people I ever realized, she touched many hearts and inspired so many others with her gladiator spirit.

Please let me know when will be next session.

Juan Camou

**Comment by pascalandy** [comment]
Juan,

So sorry for your lost. I'll host the meeting tonight.

Peace,
Pascal

**Comment by gonzalezfluz** [comment]
Juan, so, so, so sorry to hear about your loss. I can only imagine this being one of the most difficult things to have to go through. I am sending prayers and light. 

Thank you for the powerful reminders you sent our way. May we always remember to live fully. 

Mandando un gran abrazo. 
Luz

**Comment by pascalandy** [comment]
Hey guys! On on the zoom bridge number
646-568-7788, PIN: 956-624-9881

**Comment by Denisside** [comment]
Hello Juan! I just saw your note! I am so sorry for your lost! Its never easy to loose someone close to us in our family, but when its our mother, its even harder! My condolences my friend and I hope you are well! Take good care of your family and I am looking forward talking with you soon! You are in my prayers! Kind regards, Denis

**Comment by gonzalezfluz** [comment]
Juan, let us know if we can be helpful in any way. We're here for you.

Hugs,
Luz

On Tue, Jun 21, 2016 at 3:28 PM, Denis Côté notifications@github.com
wrote:

> Hello Juan! I just saw your note! I am so sorry for your lost! Its never
> easy to loose someone close to us in our family, but when its our mother,
> its even harder! My condolences my friend and I hope you are well! Take
> good care of your family and I am looking forward talking with you soon!
> You are in my prayers! Kind regards, Denis
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/pascalandy/meeting/issues/24#issuecomment-227591598,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANGrP93NDusg-72z9Rr8ffaJic6WqoeUks5qOGWggaJpZM4Iv6rS
> .

## 

_Luz C. Gonzalez_
Head of Partnerships
SchoolMint

www.luzcgonzalez.com http://luzcgonzalez.com
https://www.facebook.com/LuzCGonzalezFernandez/
https://www.linkedin.com/in/luz-c-gonzalez-fernandez-00198056
https://www.youtube.com/channel/UCM71Bn_3Ybqfe3Az6qxskvg
https://twitter.com/GonzalezfLuz?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
