### ISSUE TITLE
Session #12 (2016-06-21)

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#25]

**Comment by pascalandy** [comment]
Hey everyone!

Our next meeting should be hosted by @juancamou.

See you soon! @gonzalezfluz @Denisside @JillMurwin

**Comment by gonzalezfluz** [comment]
See you all soon!

On Wed, Jun 8, 2016 at 6:04 PM, Pascal Andy notifications@github.com
wrote:

> Hey everyone!
> 
> Our next meeting should be hosted by @juancamou
> https://github.com/juancamou.
> 
> See you soon! @gonzalezfluz https://github.com/gonzalezfluz @Denisside
> https://github.com/Denisside @JillMurwin https://github.com/JillMurwin
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/pascalandy/meeting/issues/25#issuecomment-224775718,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANGrP-EJS943aW3he8ITPNy3pOtLqt4lks5qJ2aOgaJpZM4IxjFt
> .

## 

_Luz C. Gonzalez_
Head of Partnerships
SchoolMint

www.luzcgonzalez.com http://luzcgonzalez.com
https://www.facebook.com/LuzCGonzalezFernandez/
https://www.linkedin.com/in/luz-c-gonzalez-fernandez-00198056
https://www.youtube.com/channel/UCM71Bn_3Ybqfe3Az6qxskvg
https://twitter.com/GonzalezfLuz?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

**Comment by Denisside** [comment]
Hey guys! 8:30 PM (EST) On, on the zoom bridge number
646-568-7788, PIN: 956-624-9881
