### ISSUE TITLE
Session #13 2016-06-21

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#26]
Hey guys!

I can't be here tonight. I have lucky diner with Avril and I'm going out in few minutes.

Have a good night!
Pascal

**Comment by Denisside** [comment]
Ok Pascal! Have a great night my friend!! Enjoy!! :-)

**Comment by Denisside** [comment]
Hey guys! 8:30 PM (EST) On, on the zoom bridge number
646-568-7788, PIN: 956-624-9881
