### ISSUE TITLE
Session 18 2016-08-02

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#28]
from @jillybean

The Gladiator's Mastermind

Session: 18
Time keeper: Denis
The host will be: Jill
Next meeting date: 2016-08-02 8h30PM EST
This meeting will last: 50 min
How much time per person: 6 min
Use Zoom meeting. Phone bridge: 646-568-7788, PIN:956-624-9881 https://zoom.us/zoomconference
https://github.com/pascalandy/meeting/blob/master/README.md
Pairing match for today (changing everyweek):

Pascal Andy
Denis Cote
Juan Camou
Jill Murwin
Luz Gonzalez

Here is the tool the generate a random list.

Questions & Sharing

A 30 seconds quick update:

What are you been working on?
What did you learn since our last meeting?
What are your proud of since our last meeting? What are your achievements?
Going deeper in 4 minutes:

How did it went with your goal you wanted to achieve by our next meeting (Aug 2nd)?
What can we do for you?!:)

**Comment by pascalandy** [comment]
My phone is crash ... try to join !!

**Comment by JillMurwin** [comment]
Pascal...Is this correct?:)

**Comment by pascalandy** [comment]
Yes, after one minute, I worked again LOL. Need to format it !
