### ISSUE TITLE
session 05

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/meeting#4]
- For Denis, follow up with the folks who are missing

**Comment by pascalandy** [comment]
http://www.timer-tab.com/

**Comment by pascalandy** [comment]
linked to what I learned:
https://github.com/pascalandy/connect-ghost-with-postgresql

**Comment by pascalandy** [comment]
- https://thepitch.fm/
- https://www.youtube.com/watch?v=i6O98o2FRHw

**Comment by juancamou** [comment]
www.visionandsound.tv
